server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://thtlhrooqyopfe:b40f1b63d3b864f0107a3e239b03da6ba5daf92fc15ce0c8c519abfaa9cc5a2f@ec2-3-218-71-191.compute-1.amazonaws.com:5432/dfq4h56p8mfc6b
    username: thtlhrooqyopfe
    password: b40f1b63d3b864f0107a3e239b03da6ba5daf92fc15ce0c8c519abfaa9cc5a2f
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO Santander / Backend